version: '3'
services:
  tps-test-postgres:
    image: postgres:15.2
    container_name: postgres_test
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
  tps-test-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
